# Daten-Konfiguration
data:
  raw_data_path: "data/raw/linkedin_data.csv"
  processed_data_path: "data/processed/processed_data.csv"
  target_column: "target"
  categorical_columns:
    - "industry"
    - "location"
    - "company_size"
  numerical_columns:
    - "experience_years"
    - "education_level"
    - "connections_count"
    - "posts_count"
  train_split: 0.8
  val_split: 0.1
  batch_size: 32
  num_workers: 4

# Modell-Konfiguration
model:
  input_dim: 10  # Wird automatisch berechnet
  hidden_dims: [128, 64]
  output_dim: 1
  dropout_rate: 0.2
  learning_rate: 0.001

# Training-Konfiguration
training:
  max_epochs: 100
  accelerator: "auto"
  devices: 1
  precision: 32
  log_every_n_steps: 10
  early_stopping_patience: 10
  checkpoint_dir: "checkpoints"

# Logging-Konfiguration
logging:
  log_dir: "logs"
  name: "linkedin_model"
  version: "1.0.0" 