data:
  batch_size: 32
  num_workers: 4
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

model:
  input_dim: 5  # experience_years, connections_count, account_age_days, position_level, experience_count
  hidden_dims: [64, 32, 16]
  output_dim: 8  # Anzahl der möglichen Karrierestufen
  learning_rate: 0.001
  dropout_rate: 0.2

training:
  max_epochs: 50
  accelerator: 'cpu'  # oder 'gpu' wenn verfügbar
  devices: 1
  precision: 32
  log_every_n_steps: 10

logging:
  log_dir: 'ml_pipe/logs'
  name: 'linkedin_career_prediction'
  version: '1.0.0'

callbacks:
  early_stopping:
    monitor: 'val_loss'
    patience: 5
    mode: 'min'
  model_checkpoint:
    monitor: 'val_loss'
    mode: 'min'
    save_top_k: 1
    filename: 'best_model' 